version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=horseracing
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d horseracing"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
volumes:
  postgres_db: